---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:  
     - name: Launch new instance
       ec2:
           region: us-east-2
           keypair: ansible1
           zone: us-east-2b
           group: default
           image: ami-aa1b34cf
           instance_type: t2.micro
           instance_tags:
              Name: new 
       register: ec2

     - name: Debug
       debug: 
          msg: "{{ ec2 }}"
