---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:  
     - name: Launch new instance
       ec2:
           region: us-east-2
           keypair: ansible1
           zone: us-east-2b
           group: default
           instance_ids: i-0c3f763166027475d           
           state: absent
